server:
  shutdown: GRACEFUL
  port: ${APPLICATION_HTTP_PORT:8080}
spring:
  application.name: formula-one-betting
  cloud.openfeign:
    compression.response.enabled: true
    client.config:
      openf1-api:
        connect-timeout: ${APPLICATION_HTTP_CLIENT_OPENF1_API_CONNECTION_TIMEOUT:500}
        read-timeout: ${APPLICATION_HTTP_CLIENT_OPENF1_API_READ_TIMEOUT:5000}
        #url: ${APPLICATION_HTTP_CLIENT_OPENF1_API_HOST:https://api.openf1.org}
        url: ${APPLICATION_HTTP_CLIENT_OPENF1_API_HOST:http://localhost:9090}
        logger-level: ${APPLICATION_HTTP_CLIENT_OPENF1_LOG_LEVEL:BASIC}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:betting}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:password}
  flyway:
    schemas: ${DATABASE_SCHEMA:betting}
    baseline-on-migrate: true
    baseline-version: ${FLYWAY_BASELINE_VERSION:1}
  jpa:
    database: POSTGRESQL
    open-in-view: false
    properties:
      hibernate:
        default_catalog: ${DATABASE_NAME:betting}
        default_schema: ${DATABASE_SCHEMA:betting}
        ddl-auto: validate
        format_sql: ${APPLICATION_DATABASE_JPA_DEBUG_MODE:false}
        show-sql: ${APPLICATION_DATABASE_JPA_DEBUG_MODE:false}
    show-sql: ${APPLICATION_DATABASE_JPA_DEBUG_MODE:false}
  jackson:
    deserialization:
      FAIL-ON-UNKNOWN-PROPERTIES: false
    property-naming-strategy: SNAKE_CASE
    time-zone: UTC
  lifecycle:
    timeout-per-shutdown-phase: ${APPLICATION_LIFECYCLE_SHUTDOWN_TIMEOUT_IN_SECONDS:20s}
  mvc:
    problemdetails.enabled: true
    log-request-details: ${APPLICATION_WEB_ENABLE_LOG_REQUEST:false}

management:
  tracing:
    propagation:
      type: B3
      consume: [ B3, W3C ]
      produce: B3
  endpoints:
    web.exposure:
      include: health, info
  server:
    port: ${APPLICATION_MANAGEMENT_PORT:8081}

logging:
  exception-conversion-word: "%wEx"
  level:
    com.sportygroup.betting.infrastructure.externalapi.formulaone.client:
      openf1-api: ${APPLICATION_HTTP_CLIENT_OPENF1_LOGGING_LEVEL:INFO}
    com.zaxxer.hikari: ${APPLICATION_PERSISTENCE_LOGGING_LEVEL:WARN}
    org.flyway.core: ${APPLICATION_PERSISTENCE_LOGGING_LEVEL:WARN}
    org.hibernate: ${APPLICATION_PERSISTENCE_LOGGING_LEVEL:WARN}
    org.springframework.web: ${APPLICATION_SPRING_WEB_LOGGING_LEVEL:INFO}
    org.springframework.data: ${APPLICATION_PERSISTENCE_LOGGING_LEVEL:WARN}
    org.springframework.orm.jpa: ${APPLICATION_PERSISTENCE_LOGGING_LEVEL:WARN}

springdoc:
  api-docs:
    enabled: ${APPLICATION_DOCUMENTATION_ENABLED:true} #note: usually this is only enabled on lower environment(s)!
    path: /docs/api.json
  swagger-ui:
    enabled: ${APPLICATION_DOCUMENTATION_ENABLED:true}
    default-models-expand-depth: -1
    operationsSorter: alpha
    path: /docs/api.html
    try-it-out-enabled: ${APPLICATION_DOCUMENTATION_ENABLED:true}
  writer-with-default-pretty-printer: true
  writer-with-order-by-keys: true

application.messaging.formulaone.bets.queue: formulaone-bets