CREATE SEQUENCE IF NOT EXISTS "account_id_seq" START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS "wallet_id_seq" START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS "bet_booking_id_seq" START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS "provider_datasource_id_seq" START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS ACCOUNT
(
    id    BIGINT
        CONSTRAINT "ACCOUNT_ID_PK" PRIMARY KEY DEFAULT NEXTVAL('account_id_seq'),
    email TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS WALLET
(
    id      BIGINT
        CONSTRAINT "WALLET_ID_PK" PRIMARY KEY DEFAULT NEXTVAL('wallet_id_seq'),
    balance BIGINT NOT NULL                   DEFAULT 0 CHECK (balance >= 0),
    user_id BIGINT NOT NULL
        CONSTRAINT "ACCOUNT_ID_FK" REFERENCES ACCOUNT (id)
);

CREATE TABLE IF NOT EXISTS BET_BOOKING
(
    id         BIGINT
        CONSTRAINT "BET_BOOKING_ID_PK" PRIMARY KEY DEFAULT NEXTVAL('bet_booking_id_seq'),
    wallet_id  BIGINT    NOT NULL
        CONSTRAINT "WALLET_ID_FK" REFERENCES WALLET (id),
    event_id   BIGINT    NOT NULL,
    driver_id  INTEGER   NOT NULL,
    amount     BIGINT    NOT NULL CHECK (amount > 0),
    odd        INTEGER   NOT NULL,
    created_at TIMESTAMP NOT NULL                  DEFAULT NOW(),
    completed  BOOLEAN                             DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS PROVIDER_DATASOURCE
(
    id       BIGINT
        CONSTRAINT "PROVIDER_DATASOURCE_ID_PK" PRIMARY KEY DEFAULT NEXTVAL('provider_datasource_id_seq'),
    type     TEXT NOT NULL
        CONSTRAINT "PROVIDER_DATASOURCE_TYPE_UNIQUE" UNIQUE,
    provider TEXT NOT NULL
        CONSTRAINT "PROVIDER_DATASOURCE_NAME_UNIQUE" UNIQUE
);

ALTER SEQUENCE "account_id_seq" OWNED BY ACCOUNT.id;
ALTER SEQUENCE "wallet_id_seq" OWNED BY WALLET.id;
ALTER SEQUENCE "bet_booking_id_seq" OWNED BY BET_BOOKING.id;
ALTER SEQUENCE "provider_datasource_id_seq" OWNED BY PROVIDER_DATASOURCE.id;